# This image will only contains environment which means you should
# mount a volume to the source code when creating containers.
# E.g.
# docker run --name container-name
#   -p 3001:3001
#   -v ./src:/ws/src
#   -d example-fastapi:env-only
FROM python:3.10.7-slim

COPY ["./LICENSE", "./requirements.txt", "/ws/"]

WORKDIR "/ws"
RUN [\
  "python", "-m", "pip", "install", \
  "--no-cache-dir", "--upgrade", "-r", "requirements.txt"\
]

EXPOSE 3001
WORKDIR "/ws/src/fastapi_app"
CMD ["python", "main.py"]
